django-web/camp/urls.py
from django.urls import path
from camp import views

app_name = 'camp'

urlpatterns = [
    path('', views.PageCamp.as_view(tags=['pretext']), name='camp'),
    path('more', views.PageCamp.as_view(tags=['pretext'],more=True), name='camp_more'),
]

django-web/contest/urls.py
from django.urls import path, include
from contest import views
from core.views import page_static
from contest.views import users, tasks, results, handlers

app_name = 'contest'

urlpatterns = [
    path('login/', views.users.page_login, name='login'),
    path('logout/', views.users.handler_logout, name='logout'),
    path('register/', views.users.page_register, name='register'),

    path('reset_password/', views.users.page_reset_password, name='reset_password'),
    path('reset_password/confirm/<uidb64>/<token>/', views.users.page_reset_password_confirm, name='reset_password_confirm'),
    path('reset_password/done/', views.users.page_reset_password_done, name='reset_password_done'),

    path('verification/info', views.users.PageVerificationInfo.as_view(tags=['verification']), name='verification_info'),
    path('verification/send', views.users.page_verification_send, name='verification_send'),
    path('verification/verify/<uidb64>/<str:token>', views.users.page_verification_verify, name='verification_verify'),

    path('account/view_change_password/', views.users.page_change_password, name='change_password'),
    path('account/', lambda request: views.users.page_account(request,None), name='account'),
    path('account/<str:tag>', views.users.page_account, name='account_tagged'),
    path('update_account/', views.users.page_update_account, name='update_account'),
    path('contestant/<str:username>', views.users.page_public_account, name='public_account'),

    path('forum/', include('forum.urls')),
    path('camp/', include('camp.urls')),
    
    path('', views.PageIndex.as_view(tags=['claim', 'subclaim', 'intro']), name='index'), #template_name='contest/index.html', 
    path('archive/', views.page_archive, name='archive'),

    #path('tasks/<int:contest_order>/<int:collection_order>/<int:task_order>', views.tasks.page_task, name='task'),
    path('tasks/<int:contest_order>/<int:collection_order>', views.tasks.page_task_collection, name='tasks'),
    path('tasks/', views.tasks.page_task_collection_current, name='tasks_newest'),

    #path('solutions/<int:contest_order>/<int:collection_order>', views.tasks.page_sample_solutions, name='sample_solutions'),

    path('results/<int:contest_order>/<int:collection_order>/cumulative', views.results.PageResults.as_view(cumulative=True), name='results_cumulative'),
    path('results/<int:contest_order>/<int:collection_order>', views.results.PageResults.as_view(), name='results'),
    path('results/<int:contest_order>', views.results.PageResults.as_view(), name='results_contest'),
    path('results/', views.results.PageResults.as_view(), name='results_newest'),

    path('old_contribs/', views.PageOldContribs.as_view(), name='old_contribs_def'),
    path('old_contribs/<int:page_no>', views.PageOldContribs.as_view(), name='old_contribs'),
    path('rules/', views.PageRules.as_view(tags=['rules']), name='rules'),
    path('about/', views.PageAboutUs.as_view(tags=['about']), name='about'),
    #path('other_seminars/', views.PageOtherSeminars.as_view(tags=['other_seminars']), name='other_seminars'),
    path('how_to/', views.PageHowTo.as_view(tags=['how_to']), name='how_to'),
    path('user/submission/<int:contest_order>/<int:collection_order>/<int:task_order>', handlers.user_submission, name='user_submission'),
    path('user/submission/<int:contest_order>/<int:collection_order>/<int:task_order>/delete', handlers.user_submission_delete, name='user_submission_delete'),
    path('user/submission/<int:contest_order>/<int:collection_order>/<int:task_order>/write', views.page_write_submission, name='user_submission_write'),
    path('user/submission/<int:contest_order>/<int:collection_order>/<int:task_order>/save', handlers.user_submission_save, name='user_submission_save'),

    path('page/<path:path>', page_static, name='static_page'),
]

django-web/core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', include('smuggler.urls')),
    path('admin/', admin.site.urls),

    path('api/md_to_html', views.handler_markdown_to_html, name='md_to_html'),
    path('api/latex_to_html', views.handler_latex_to_html, name='latex_to_html'),
    path('api/', include('contest.api')),

    path('mathrace/', include('mathrace.urls', namespace='mathrace')),
    path('', include('contest.urls', namespace='brkos')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path('%s<path:path>' % settings.PRIVATE_URL, views.private_serve, {'document_root': settings.PRIVATE_ROOT}),
    path('%s<path:path>' % settings.PROTECTED_URL, views.protected_serve, {'document_root': settings.PROTECTED_ROOT}),
]

django-web/contest/views/handlers.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http import Http404, HttpResponse, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.template.loader import select_template
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.utils import timezone
from django.db.models import Prefetch
from django.db.models.functions import Lower

from contest.models import Contest, TaskCollection, TaskFileSubmission, Task, Contestant
from core.forms import UploadForm
from core.models import MediaFile, Organizer, ContestType
from forum.models import Contribution
from django.views.generic import TemplateView

from core.views import EditablePage, render_editable
from django.forms import Form

import json

"""
Views
"""

@staff_member_required(redirect_field_name='/')
def collection_file_upload(request, collection_id):
    form = UploadForm(['pdf'],4,request.POST,request.FILES)
    if not form.is_valid():
        return HttpResponseForbidden(form.errors["file"])

    f = request.FILES['file']
    collection = get_object_or_404(TaskCollection, pk=collection_id)
    file_type = request.GET["file_type"]
    attrname = f"{file_type}_pdf"
    target_filename = f'brkos/{file_type}_{collection.contest.order}_{collection.order}'

    collection.upload_file(attrname, f, target_filename, [request.user], 1)

    return HttpResponse('Soubor byl úspěšně nahrán.')


@staff_member_required(redirect_field_name='/')
def feedback_upload(request, submission_id):
    form = UploadForm(['pdf','jpg','jpeg','png'],4,request.POST,request.FILES)
    if not form.is_valid():
        return HttpResponseForbidden(form.errors["file"])

    f = request.FILES['file']
    submission = get_object_or_404(TaskFileSubmission, pk=submission_id)
    target_filename = 'feedbacks/'+submission.compose_file_name_feedback()

    submission.upload_file('feedback_file', f, target_filename, owners=[submission.contestant.user, request.user])

    return HttpResponse('Soubor byl úspěšně nahrán.')


@staff_member_required(redirect_field_name='/')
def multiple_upload(request, task_id):
    
    task = get_object_or_404(Task, pk=task_id)
    problem_files = []

    for fname, f in request.FILES.items():
        info = fname.split('_')

        try:
            submission = TaskFileSubmission.get_from_id62(info[0])

            target_filename = 'feedbacks/'+submission.compose_file_name_feedback()

            submission.upload_file('feedback_file', f, target_filename, owners=[submission.contestant.user, request.user])
        except:
            problem_files.append(fname)

    if len(problem_files) == 0:
        return HttpResponse('Soubor byl úspěšně nahrán.')
    else:
        msg = 'Některé soubory se nepodařilo nahrát:'
        for pf in problem_files: msg += '\n'+pf
        return HttpResponse(msg)


@login_required(redirect_field_name='/')
def user_submission(request, contest_order, collection_order, task_order):
    """
    Uploads contestant task submission to the private storage.
    Creates a new submission object in the database.

    Fails if contest, collection or task does not exist or the collection is not active.

    Privacy policy: LOGIN_REQUIRED

    :param request: HTTP request
    :param contest_order: (int)  order of the contest
    :param collection_order: (int) order of the collection int the contest
    :param task_order: (int) order of the task in the collection
    :return: HTTP response
    """

    form = UploadForm(['pdf','jpg','jpeg','png'],4,request.POST,request.FILES)
    if not form.is_valid():
        return HttpResponseForbidden(form.errors["file"])

    f = request.FILES['file']

    task = Task.objects.get(
        collection__order=collection_order,
        collection__contest__order=contest_order,
        order=task_order
    )

    if task.collection.is_closed():
        return HttpResponseForbidden('Nelze odevzdávat po uzavření série.')

    try:
        contestant = request.user.contestant
    except ObjectDoesNotExist:
        return HttpResponseForbidden('Může odevzdávat pouze registrovaný soutěžící.')

    if not contestant.is_allowed():
        return HttpResponseForbidden('Může odevzdávat pouze student střední školy.')

    try:
        submission = TaskFileSubmission.objects.get(contestant=contestant, task=task)
        try:
            submission.content.delete()
        except:
            pass
    except ObjectDoesNotExist:
        submission = TaskFileSubmission(
            contestant=contestant,
            task=task,
        )
        submission.save()

    media_file = MediaFile.objects.create(
        content=f,
        access=2,
        name="submissions/"+submission.compose_file_name()
    )

    media_file.owners.add(request.user)

    submission.score = None
    submission.content = media_file
    submission.save()

    return HttpResponse('Soubor byl úspěšně nahrán.')


@login_required(redirect_field_name='/')
def user_submission_delete(request, contest_order, collection_order, task_order):

    task = Task.objects.get(
        collection__order=collection_order,
        collection__contest__order=contest_order,
        order=task_order
    )

    if task.collection.is_closed():
        return HttpResponseForbidden('Nelze smazat řešení po uzavření série.')

    try:
        contestant = request.user.contestant
    except ObjectDoesNotExist:
        return HttpResponseForbidden('Může odevzdávat pouze registrovaný soutěžící.')

    if not contestant.is_allowed():
        return HttpResponseForbidden('Může odevzdávat pouze student střední školy.')

    try:
        submission = TaskFileSubmission.objects.get(contestant=contestant, task=task)
        submission.content.delete()
    except ObjectDoesNotExist:
        return HttpResponseForbidden('Nebyla dříve odevzdána žádná úloha.')

    submission.content = None
    submission.save()
    submission.delete_if_empty()

    return HttpResponse('Soubor byl odstraněn.')


@login_required(redirect_field_name='/')
def user_submission_save(request, contest_order, collection_order, task_order):

    content = request.POST['submission']

    task = Task.objects.get(
        collection__order=collection_order,
        collection__contest__order=contest_order,
        order=task_order
    )

    if task.collection.is_closed():
        return HttpResponseForbidden('Nelze odevzdat řešení po uzavření série.')

    try:
        contestant = request.user.contestant
    except ObjectDoesNotExist:
        return HttpResponseForbidden('Může odevzdávat pouze registrovaný soutěžící.')

    if not contestant.is_allowed():
        return HttpResponseForbidden('Může odevzdávat pouze student střední školy.')

    try:
        submission = TaskFileSubmission.objects.get(contestant=contestant, task=task)
    except ObjectDoesNotExist:
        submission = TaskFileSubmission(
            contestant=contestant,
            task=task
        )

    submission.online_submission = content
    submission.save()
    submission.delete_if_empty()

    return HttpResponse('Řešení bylo uloženo.')

django-web/contest/views/results.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.views.generic import TemplateView

from contest.models import Contest, TaskCollection, ResultsTable
from core.models import PublishableModel
from core.utils import int_to_roman

"""
Helpers
"""


def render_latex_results(request, head, res, contest, collection=None, cumulative=False):
    template_name = 'contest/latex/results.tex'

    contest_year_roman = int_to_roman(contest.order)
    if cumulative:
        title = 'Výsledky po {}. sérii {}. ročníku'.format(collection.order, contest_year_roman)
    else:
        title = 'Výsledky {}. série {}. ročníku'.format(collection.order, contest_year_roman)

    column_definition = '|r|l|c|l|' + 'c|' * (len(head)-4)

    context = {
        'collection': collection,
        'contest': contest,
        'head': head,
        'results': res,
        'column_definition': column_definition,
        'title': title,
    }

    return HttpResponse(render_to_string(template_name, context), content_type='text/plain')


"""
Views
"""


def find_collection(contest_order=None, collection_order=None):
    try:
        if contest_order is None:
            contest = Contest.public_objects()\
                .order_by('-order').first()
        else:
            contest = Contest.public_objects().get(order=contest_order)
    except (ObjectDoesNotExist, IndexError):
        raise Http404("Soutěž nenalezena.")

    if collection_order is None:
        collection = TaskCollection.current_collection_with_results()
    else:
        collection = contest.task_collections.filter(PublishableModel.q_public(), order=collection_order).last()
    if collection is None:
        raise Http404("Pro tuto soutěž zatím není zveřejněna žádná série.")

    return contest, collection


class PageResults(TemplateView):
    template_name = 'contest/results.html'
    cumulative = False

    def get_context_data(self, **kwargs):
        contest, collection = find_collection(kwargs.get('contest_order', None),
                                              kwargs.get('collection_order', None))
        table = ResultsTable(contest, collection)
        if collection.release_results:
            if self.cumulative:
                head, res = table.get_results_cumulative()
            else:
                head, res = table.get_results_collection()
        else:
            res = []
            head = []

        contests = Contest.objects.all()
        collections = contest.task_collections.all()

        return {
            'results': res,
            'displayed_contest': contest,
            'displayed_collection_order': collection.order,
            'contests': contests,
            'task_collections': collections,
            'this_contest_order': contest.order,
            'head': zip(range(1, len(head) + 1), head),
            'cumulative': self.cumulative,
        }


def handler_latex_results_cumulative(request, id):
    collection = get_object_or_404(TaskCollection, pk=id)
    head, res = ResultsTable(collection.contest, collection).get_results_cumulative()
    return render_latex_results(request, head, res, collection.contest, collection, cumulative=True)


def handler_latex_results(request, id):
    collection = get_object_or_404(TaskCollection, pk=id)
    head, res = ResultsTable(collection.contest, collection).get_results_collection()
    return render_latex_results(request, head, res, collection.contest, collection)

django-web/contest/templates/contest/parts/feedback_upload.html
<form id="{{ submission.id }}-form" action="">
    <input id="{{submission.id}}-file-dialog"
           type="file" style="display:none"
           onchange="cmp.upload('#{{submission.id}}-file-dialog', '{% url 'feedback_upload' submission_id=submission.id %}?file_type=')"/>
</form>

<table>
    <tr>
        <td><a class="button" onclick="$('#{{submission.id}}-file-dialog').trigger('click');">
            <i class="fas fa-file-upload"></i>
        </a></td>
    </tr>
    <tr>
        <td>{% if submission.feedback_file %}
            <a class="button" target="_blank" href={{submission.feedback_file.url}}><i class="fas fa-file-pdf"></i></a>
        {% endif %}</td>
    </tr>
</table>

django-web/contest/templates/contest/parts/inline_clock.html
{% if active_collection.is_open %}

    <script>
    $(()=>{
// Set the date we're counting down to
var countDownDate = new Date("{{ active_collection.close_date.isoformat }}").getTime();

// Update the count down every 1 second
var countDown = setInterval(function() {
  // Get today's date and time
  var now = new Date().getTime();

  // Find the distance between now and the count down date
  var distance = countDownDate - now;
  distance = distance < 0 ? 0 : distance;
  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Display the result in the element with id="demo"
  document.getElementById("days").innerHTML = days;
  document.getElementById("hours").innerHTML = hours;
  document.getElementById("minutes").innerHTML = minutes;
  document.getElementById("seconds").innerHTML = seconds;
}, 1000);
});
</script>
<div class="flex flex-col w-full">
  <div class="grid flex-grow h-24 place-items-center">
    <div class="grid grid-flow-col gap-5 text-center auto-cols-max">
      <div class="flex flex-col mr-6">
        <span class="font-mono text-5xl lg:text-6xl">
          <span id="days">0</span>
        </span>
            dní
      </div>
      <div class="flex flex-col mr-2">
        <span class="font-mono text-5xl lg:text-6xl">
          <span id="hours">0</span>
        </span>
            hodin
      </div>
      <div class="flex flex-col mr-2">
        <span class="font-mono text-5xl lg:text-6xl">
          <span id="minutes">0</span>
        </span>
            minut
      </div>
      <div class="flex flex-col">
        <span class="font-mono text-5xl lg:text-6xl">
          <span id="seconds">0</span>
        </span>
            sekund
      </div>
    </div>
  </div>
  <div class="w-full text-center text-2xl">do uzavření <a class="text-secondary" href="{% url 'contest:tasks_newest' %}">příští série</a></div>
</div>
{% else %}
{% endif %}

django-web/contest/templates/contest/parts/large_clock.html
{% if active_collection.is_open %}

    <script>
    $(()=>{
// Set the date we're counting down to
var countDownDate = new Date("{{ active_collection.close_date.isoformat }}").getTime();

// Update the count down every 1 second
var countDown = setInterval(function() {
  // Get today's date and time
  var now = new Date().getTime();

  // Find the distance between now and the count down date
  var distance = countDownDate - now;
  distance = distance < 0 ? 0 : distance;
  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Display the result in the element with id="demo"
  document.getElementById("days").innerHTML = days;
  document.getElementById("hours").innerHTML = hours;
  document.getElementById("minutes").innerHTML = minutes;
  document.getElementById("seconds").innerHTML = seconds;
}, 1000);
});
</script>
<div class="flex flex-row w-full">
  <div class="grid flex-grow h-32 place-items-center"><span class=" w-full text-right text-5xl">Zbývá</span><br>
    <span class="w-full text-right text-2xl">Do uzavření <a class="text-primary" href="{% url 'contest:tasks_newest' %}">příští série</a></span></div>
  <div class="divider divider-vertical"></div>
  <div class="grid flex-grow h-32 place-items-center">
    <div class="grid grid-flow-col gap-5 text-center auto-cols-max">
      <div class="flex flex-col">
        <span class="font-mono text-5xl lg:text-6xl">
          <span id="days">0</span>
        </span>
            dní

      </div>
      <div class="flex flex-col">
        <span class="font-mono text-5xl lg:text-6xl">
          <span id="hours">0</span>
        </span>
            hodin

      </div>
      <div class="flex flex-col">
        <span class="font-mono text-5xl lg:text-6xl">
          <span id="minutes">0</span>
        </span>
            minut

      </div>
      <div class="flex flex-col">
        <span class="font-mono text-5xl lg:text-6xl">
          <span id="seconds">0</span>
        </span>
            sekund

      </div>
    </div>
  </div>
</div>
{% else %}
{% endif %}

django-web/contest/templates/contest/parts/registration_form.html
{% load extras %}

<form method="POST" class="block mx-auto text-center max-w-sm">
    {% csrf_token %}
    <h1 class="my-10">Registrace</h1>

    {% if request|namespace_prefix == "mathrace" %}
        <div class="alert alert-info my-2 p-3 text-sm block text-justify">Neregistrujte se prosím zbytečně znovu. Můžete se <a href="{% url 'mathrace:login' %}" class="inline link-secondary">přihlásit</a> účtem od BRKOSu, příp. účtem z minulého roku.</div>
    {% else %}
        <div class="alert alert-warning my-2 p-3 text-sm block text-justify">Neregistrujte se prosím zbytečně znovu. Po přechodu na nový web zůstaly všechny uživatelské účty v platnosti.
        Pokud jste již na našem starém webu účet měli, pouze <a href="{% url 'contest:reset_password' %}" class="inline link-secondary">si prosím obnovte heslo</a>.</div>
    {% endif %}
    
    {% include 'core/parts/form.html' with form=registration_form %}
    
    {% if contestant_form %}
        <div class="divider">Škola</div>
        {% include 'core/parts/form.html' with form=contestant_form %}
    {% endif %}

    <button type="submit" class="btn my-10 btn-block btn-primary">Registruj se!</button>
</form>

django-web/contest/templates/contest/parts/story.html
{% load extras %}

<latex-js class="story">
    <p>{{ story | gen_file_refs | markdown_to_html | safe }}</p>
</latex-js>

django-web/contest/templates/contest/parts/submissions_list.html
{% load extras %}

<table class="w-full table my-10">
    <thead>
    <tr><th class="">Úloha</th><th class="">Náhled</th><th class="">Body</th><th class="">Komentář</th></tr>
    </thead>
    <tbody class="">
    {% for sub in submissions %}
    <tr class="item border-t-2 border-base-300">
        <td>{{sub.task}}</td>
        <td><a target="_blank" class="btn-primary btn btn-sm" href="{{sub.content.url}}"><i class="fa fa-file-pdf"></i></a></td>
        <td class="">{{sub.score|default_if_none:"?"}}</td>
        <td>
            {% if sub.feedback_file %}
            <a target="_blank" class="btn-accent btn btn-sm" href="{{sub.feedback_file.url}}"><i class="fa fa-file-pdf"></i></a>
            <br>
            {% endif %}
        </td>
    {% if sub.feedback_text %}
    <tr><td colspan="4" class="p-2 rounded-sm bg-base-200" class="font-math italic math-text">{{sub.feedback_text | gen_file_refs | markdown_to_html | safe}}</td></tr>
    {% endif %}
    {% endfor %}
    </tbody>
</table>
{% if not old %}
    <p class="links-secondary"><a href="{% url 'contest:account_tagged' tag='old' %}">Zobrazit i řešení z minulých ročníků</a></p>
{% endif %}

django-web/contest/templates/contest/parts/task.html
{% load extras %}


<div class="card w-full bg-base-200 shadow-inner my-10 overflow-visible links-secondary">
    <div class="card-body w-full">
        <h4 class="font-bold">Úloha {{ task.name }}:</h4>
        <div class="font-math italic math-text">
            {{ task.text | gen_file_refs | markdown_to_html | safe }}
        </div>
        {% if task.online_submission %}
        <h4 class="font-bold mt-3">Moje řešení</h4>
            <div class="font-math italic math-text">
                <div id="submission_{{ task.order }}">{{ task.online_submission | gen_file_refs | markdown_to_html | safe }}</div>
            </div>
        {% endif %}
        {% if collection.release_solution %}
            <h4 class="font-bold mt-3"><a class="cursor-pointer" onclick="$('#solution_{{ task.order }}').toggle()">Řešení</a></h4>
            <div class="font-math italic math-text">
                <div id="solution_{{ task.order }}" class="hidden">{{ task.model_solution | gen_file_refs | markdown_to_html | safe }}</div>
            </div>
                {% if task.comment %}
                    <h4 class="font-bold mt-3"><a class="cursor-pointer" onclick="$('#comment_{{ task.order }}').toggle()">Komentář</a></h4>
                    <div class="font-math italic math-text">
                        <div id="comment_{{ task.order }}" class="hidden">{{ task.comment | gen_file_refs | markdown_to_html | safe }}</div>
                    </div>
                {% endif %}
        {% endif %}

        <div class="card-actions justify-end flex-col md:flex-row">
            {% if task.online_submission %}
                <div class="btn btn-secondary btn-outline mr-3 ml-0" onclick="window.open('{% url 'contest:user_submission_write' contest_order=contest.order collection_order=collection.order task_order=task.order %}');">
                    Upravit řešení <i class="fas fa-pen ml-4"></i>    
                </div>
            {% endif %}
            {% if task.submission_url %}
                <div onclick="window.open('{{ task.submission_url }}');" class="btn btn-secondary btn-outline mr-3 ml-0">
                    Nahrané řešení <i class="fas fa-file-alt ml-4"></i>
                </div>
                <div class="btn border-error text-error hover:bg-error hover:text-base-100 hover:border-error btn-outline mr-3 ml-0" onclick="cmp.request_reload('{% url 'contest:user_submission_delete' contest_order=contest.order collection_order=collection.order task_order=task.order %}')">
                    Smazat soubor <i class="fas fa-trash ml-4"></i>    
                </div>
            {% endif %}  

            {% if collection.is_open %}
                <form id="task-{{task.order}}-form" action="" class="hidden">
                    <input id="task-{{task.order}}-file-dialog"
                        type="file" style="display:none"
                        onchange="cmp.upload_reload('#task-{{task.order}}-file-dialog', '{% url 'contest:user_submission' contest_order=contest.order collection_order=collection.order task_order=task.order %}')"/>
                </form>

                {% if not user.is_authenticated %}
                <a class="btn btn-primary ml-0 hidden md:inline-flex" style="color: white; text-decoration: none;" href="#my-modal">
                    Odevzdat <i class="fas fa-file-import"></i>    
                </a>
                <a class="btn btn-primary ml-0 md:hidden" style="color: white; text-decoration: none;" href="{% url 'contest:login' %}?next=/tasks/">
                    Odevzdat <i class="fas fa-file-import"></i>    
                </a>
                {% elif user.to_be_verified %}
                <a class="btn btn-primary ml-0 inline-flex" style="color: white; text-decoration: none;" href="{% url 'contest:verification_info' %}">
                    Odevzdat <i class="fas fa-file-import"></i>    
                </a>
                {% else %}
                <div class="dropdown dropdown-end mx-0 hidden md:inline-block">
                    <label class="btn btn-primary" tabindex="0">Odevzdat <i class="fas fa-file-import"></i></label>
                    <ul class="dropdown-content menu shadow rounded-box w-44 bg-base-100" tabindex="0">
                        <li class="text-primary ml-0"><div class="btn btn-ghost leading-6 hover:bg-primary hover:text-base-100" style="padding: 12px" onclick="$('#task-{{task.order}}-file-dialog').trigger('click');">
                            Nahrát soubor <i class="fas fa-file-upload ml-4"></i>    
                        </div></li>
                        <li class="text-primary ml-0"><div class="btn btn-ghost leading-6 hover:bg-primary hover:text-base-100" style="padding: 12px" onclick="window.open('{% url 'contest:user_submission_write' contest_order=contest.order collection_order=collection.order task_order=task.order %}');">
                            Napsat řešení <i class="fas fa-pen ml-4"></i>    
                        </div></li>
                    </ul>
                </div>

                <div class="dropdown mx-0 md:hidden">
                    <label class="btn btn-primary" tabindex="0">Odevzdat <i class="fas fa-file-import"></i></label>
                    <ul class="dropdown-content menu shadow rounded-box w-44 bg-base-100" tabindex="0">
                        <li class="text-primary ml-0"><div class="btn btn-ghost leading-6 hover:bg-primary hover:text-base-100" style="padding: 12px" onclick="$('#task-{{task.order}}-file-dialog').trigger('click');">
                            Nahrát soubor <i class="fas fa-file-upload ml-4"></i>    
                        </div></li>
                        <li class="text-primary ml-0"><div class="btn btn-ghost leading-6 hover:bg-primary hover:text-base-100" style="padding: 12px" onclick="window.open('{% url 'contest:user_submission_write' contest_order=contest.order collection_order=collection.order task_order=task.order %}');">
                            Napsat řešení <i class="fas fa-pen ml-4"></i>    
                        </div></li>
                    </ul>
                </div>

                {% endif %}
            {% endif %}       
        </div>
    </div>
</div>