django-web/camp/urls.py
from django.urls import path
from camp import views

app_name = 'camp'

urlpatterns = [
    path('', views.PageCamp.as_view(tags=['pretext']), name='camp'),
    path('more', views.PageCamp.as_view(tags=['pretext'],more=True), name='camp_more'),
]

django-web/core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', include('smuggler.urls')),
    path('admin/', admin.site.urls),

    path('api/md_to_html', views.handler_markdown_to_html, name='md_to_html'),
    path('api/latex_to_html', views.handler_latex_to_html, name='latex_to_html'),
    path('api/', include('contest.api')),

    path('mathrace/', include('mathrace.urls', namespace='mathrace')),
    path('', include('contest.urls', namespace='brkos')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path('%s<path:path>' % settings.PRIVATE_URL, views.private_serve, {'document_root': settings.PRIVATE_ROOT}),
    path('%s<path:path>' % settings.PROTECTED_URL, views.protected_serve, {'document_root': settings.PROTECTED_ROOT}),
]

django-web/forum/urls.py
from django.urls import path
from forum.views import TopicsListView, ThreadView, PostView, CommentView, handler_delete, handler_respond, handler_ban

app_name = 'forum'

urlpatterns = [
    path('', TopicsListView.as_view(), name='topics'),
    path('threads/<int:pk>', ThreadView.as_view(), name='thread'),
    #path('threads/<int:pk>/response', ThreadView.as_view(), name='thread_response'),
    #path('threads/<int:pk>/posts/<int:post_pk>/delete', PostView.as_view(), name='post_delete'),
    #path('threads/<int:pk>/posts/<int:post_pk>/response', PostView.as_view(), name='post_response'),
    #path('threads/<int:pk>/comment/<int:comment_pk>/delete', CommentView.as_view(), name='comment_delete'),
    path('delete/<int:post_pk>', handler_delete, name='delete'),
    path('ban/<int:post_pk>', handler_ban, name='ban'),
    path('respond/<int:parent_pk>', handler_respond, name='respond'),
]

django-web/forum/models.py
from django.db import models

from core.models import PublishableModel, User, RichTextField, Organizer, ContestType


class Topic(PublishableModel):
    class Meta:
        verbose_name = 'téma'
        verbose_name_plural = 'témata'
    title = models.CharField("název", max_length=64)
    private = models.BooleanField("interní",default=False)
    contest_type = models.ForeignKey(ContestType, on_delete=models.PROTECT, verbose_name="soutěž", null=True)

    def __str__(self):
        return self.title


class Text(PublishableModel):
    class Meta:
        verbose_name = 'text'
        verbose_name_plural = 'texty'

    author = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="autor", null=True)
    text = models.TextField("text")

    deleted = models.BooleanField('smazáno', default=False)
    banned = models.BooleanField("zabanováno", default=False)


class Thread(Text):
    class Meta:
        verbose_name = 'vlákno'
        verbose_name_plural = 'vlákna'

    title = models.CharField("název", max_length=128, null=True, blank=True)
    topic = models.ForeignKey(
        Topic,
        on_delete=models.PROTECT,
        related_name='threads',
        verbose_name='téma',
        null=True,
        blank=True
    )


class Post(Text):
    class Meta:
        verbose_name = 'příspěvek'
        verbose_name_plural = 'příspěvky'

        ordering = ['id']

    parent = models.ForeignKey(
        Thread,
        on_delete=models.CASCADE,
        related_name='children',
        verbose_name="rodič",
    )


class Comment(Text):
    class Meta:
        verbose_name = 'komentář'
        verbose_name_plural = 'komentáře'

        ordering = ['id']

    parent = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='children',
        verbose_name="rodič",
    )


class TagField(models.TextField):
    pass


class Contribution(PublishableModel):
    class Meta:
        verbose_name = 'novinka'
        verbose_name_plural = 'novinky'
        ordering = ['-public_from', '-created']

    contest_type = models.ForeignKey(ContestType, on_delete=models.PROTECT, verbose_name='soutěž', null=True, help_text="<p>Soutěž, ke které novinka patří</p>")
    title = models.CharField('nadpis', max_length=60)
    text = RichTextField('text novinky')
    author = models.ForeignKey(Organizer, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='autor')
    tags = TagField('tagy', default="", blank=True)

    def tag_list(self):
        return [t.strip().split('#') if '#' in t else (t, None) for t in self.tags.split(',') if t.strip()]

    def tag_list_str(self):
        tags = self.tag_list()
        if not tags:
            return ''
        else:
            return ' | '.join(list(zip(*tags))[0])

django-web/forum/forms.py
from django import forms

from forum.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text']

    text = forms.CharField()


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

    text = forms.CharField()

django-web/forum/views.py
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.db.models import Prefetch
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required

from core.models import ContestType
from forum.forms import PostForm, CommentForm
from forum.models import Topic, Post, Thread, Comment, Text


class TopicsListView(ListView):
    model = Topic
    paginate_by = 20
    context_object_name = 'topics'

    def get_queryset(self):
        contest_type_abbreviation = self.request.resolver_match.namespace.split(":")[0]

        try:
            contest_type = ContestType.objects.get(abbreviation=contest_type_abbreviation)
        except ObjectDoesNotExist:
            raise Http404("Typ soutěže nenalezen.")

        if self.request.user.is_staff:
            queryset = Topic.objects.filter(contest_type=contest_type).all()
        else:
            queryset = Topic.public_objects().filter(contest_type=contest_type, private=False)
        return queryset.order_by('title').prefetch_related(
            Prefetch('threads', queryset=Thread.objects.all())
        ).all()


class DetailThreadView(DetailView):
    model = Thread

    def get_queryset(self, **kwargs):
        if self.request.user.is_staff:
            queryset = Thread.objects.all()
        else:
            queryset = Thread.objects.filter(topic__in=Topic.public_objects())

        return queryset.prefetch_related(
            Prefetch('children', queryset=Post.objects.prefetch_related(
                Prefetch('children', queryset=Comment.objects.all())
            ))
        )


class ThreadView(DetailThreadView):
    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST)

        thread = get_object_or_404(Thread, pk=self.kwargs['pk'])
        if not thread.topic.is_public() and not request.user.is_staff:
            raise PermissionDenied()

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.parent_id = kwargs['pk']
            post.published = True
            post.save()
        else:
            pass

        return self.get(request, args, kwargs)


class PostView(DetailThreadView):
    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)

        parent = get_object_or_404(Post, pk=self.kwargs['post_pk'])
        if not parent.parent.topic.is_public and not request.user.is_staff:
            raise PermissionDenied()

        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.parent_id = kwargs['post_pk']
            comment.published = True
            comment.save()
        else:
            pass

        return self.get(request, args, kwargs)
    
    def delete(self, request, *args, **kwargs):
        post = Post.objects.get(pk=self.kwargs['post_pk'])
        if request.user.id != post.author_id:
            raise PermissionDenied()

        post.deleted = true
        post.save()

        return self.get(request, args, kwargs)

class CommentView(DetailThreadView):
    def delete(self, request, *args, **kwargs):
        post = Comment.objects.get(pk=self.kwargs['comment_pk'])
        if request.user.id != post.author_id:
            raise PermissionDenied()

        post.deleted = true
        post.save()

        return self.get(request, args, kwargs)


@login_required(redirect_field_name='/')
def handler_delete(request,post_pk):
    try:
        post = Text.objects.get(pk=post_pk)
    except:
        HttpResponseForbidden()
    
    if request.user.id != post.author_id:
            raise PermissionDenied()

    post.deleted = True
    post.save()

    return HttpResponse()


@login_required(redirect_field_name='/')
def handler_respond(request,parent_pk):
    if not request.user.verified:
        HttpResponseForbidden()

    try:
        text = request.POST["text"]
    except:
        HttpResponseForbidden()

    try:
        parent = Thread.objects.get(pk=parent_pk)
        Post.objects.create(text=text,author=request.user,parent=parent,published=True)
    except:
        try:
            parent = Post.objects.get(pk=parent_pk)
            Comment.objects.create(text=text,author=request.user,parent=parent,published=True)
        except:
            try:
                parent = Comment.objects.get(pk=parent_pk).parent
                Comment.objects.create(text=text,author=request.user,parent=parent,published=True)
            except:
                HttpResponseForbidden()

    return HttpResponse()


@login_required(redirect_field_name='/')
def handler_ban(request,post_pk):
    if not request.user.is_staff:
        PermissionDenied()

    try:
        post = Text.objects.get(pk=post_pk)
    except:
        HttpResponseForbidden()

    post.banned = not post.banned
    post.save()

    return HttpResponse()

django-web/forum/templates/forum/thread_detail.html
{% extends "core/base.html" %}
{% load extras %}
{% load static %}


{% block title %} fórum {% endblock %}

{% block content %}
<section class="center-block py-10">
        {% if not request.user.is_verified %}
        <div class="alert alert-warning">Do fóra může přispívat pouze přihlášený a ověřený uživatel.</div>
        {% endif %}

        <article class="max-w-screen-md mx-auto my-5 card compact bg-base-200 text-base-content shadow-inner relative">
            <div id="post-{{ thread.id }}" class="-my-20 absolute"></div>
            <div class="card-body">
                <h3 class="inline-block font-semibold">{{ thread.title }}</h3>
                <div class="divider divider-thin"></div>
                <div>
                    <div class="font-light text-xs inline-block float-left"> {{ thread.created }}
                    <span>{% if thread.author %}@{{ thread.author.username }}{% endif %}</span>
                    </div>
                </div>
                <div class="max-w-4/5">
                    {{ thread.text }}
                </div>
            </div>
        </article>

        
        <div class="divider divider-thin"></div>
  
        {% for post in thread.children.all %}

        {% include 'forum/parts/post_card.html' with post=post form_id=post.id %}

        <div class="ml-10">
        {% for comment in post.children.all %}
        {% include 'forum/parts/post_card.html' with post=comment type="comment" form_id=comment.id resp=comment.id %}
        {% endfor%}
        </div>
        {% endfor%}
        
        {% if user.is_verified %}
        <div id="write-new-post" class="btn btn-primary w-full mt-3" onclick="show_new_post()">Napsat příspěvek</div>
        <div id="form-new-post" class="max-w-screen-md mx-auto card compact bg-base-100 text-base-content hidden" >
            <div class="card-body">
                <textarea name="text" class="w-full textarea textarea-bordered my-1" id="response-{{thread.id}}"></textarea>
                <div class="w-full btn btn-outline btn-primary my-1" onclick="cmp.message_reload('#response-{{thread.id}}','{% url 'forum:respond'|prefix_reverse:request parent_pk=thread.id %}');">Odeslat</div>
            </div>
        </div>
        {% endif %}

        <div id="anchor" class="relative" style="bottom: 90vh;"></div>
</section>

<script>
    $(document).ready(function(){
        $("#anchor")[0].scrollIntoView();
    });

    show_new_post = function()
    {
        $('#form-new-post').show();
        $('#write-new-post').hide();
        $('#anchor')[0].scrollIntoView();
    }
</script>

{% endblock %}

django-web/forum/templates/forum/topic_list.html
{% extends "core/base.html" %}
{% load extras %}
{% load static %}


{% block title %} fórum {% endblock %}

{% block content %}
<section class="center-block py-10 lg:py-20">
    <h1 class="text-center">Diskuzní fórum</h1>
{% for topic in topics %}
    <div class="card my-8 shadow-inner bg-base-200">
        <div class="card-body">
            <h2 class="card-title text-center">{{topic.title}}</h2>
            <div class="divider my-2">Vlákna</div>
            <ol class="">
                {% for thread in topic.threads.all %}
                        <li><a class="my-2 btn btn-block btn-primary" href="{% url 'forum:thread'|prefix_reverse:request pk=thread.id %}"><p class="m-auto truncate"><i class="fa fa-comments"></i>&ensp;{{thread.title}}</p></a></li>
                {% endfor %}
            </ol>
        </div>
    </div>
{% endfor %}
</section>

{% endblock %}