django-web/camp/urls.py
from django.urls import path
from camp import views

app_name = 'camp'

urlpatterns = [
    path('', views.PageCamp.as_view(tags=['pretext']), name='camp'),
    path('more', views.PageCamp.as_view(tags=['pretext'],more=True), name='camp_more'),
]

django-web/contest/urls.py
from django.urls import path, include
from contest import views
from core.views import page_static
from contest.views import users, tasks, results, handlers

app_name = 'contest'

urlpatterns = [
    path('login/', views.users.page_login, name='login'),
    path('logout/', views.users.handler_logout, name='logout'),
    path('register/', views.users.page_register, name='register'),

    path('reset_password/', views.users.page_reset_password, name='reset_password'),
    path('reset_password/confirm/<uidb64>/<token>/', views.users.page_reset_password_confirm, name='reset_password_confirm'),
    path('reset_password/done/', views.users.page_reset_password_done, name='reset_password_done'),

    path('verification/info', views.users.PageVerificationInfo.as_view(tags=['verification']), name='verification_info'),
    path('verification/send', views.users.page_verification_send, name='verification_send'),
    path('verification/verify/<uidb64>/<str:token>', views.users.page_verification_verify, name='verification_verify'),

    path('account/view_change_password/', views.users.page_change_password, name='change_password'),
    path('account/', lambda request: views.users.page_account(request,None), name='account'),
    path('account/<str:tag>', views.users.page_account, name='account_tagged'),
    path('update_account/', views.users.page_update_account, name='update_account'),
    path('contestant/<str:username>', views.users.page_public_account, name='public_account'),

    path('forum/', include('forum.urls')),
    path('camp/', include('camp.urls')),
    
    path('', views.PageIndex.as_view(tags=['claim', 'subclaim', 'intro']), name='index'), #template_name='contest/index.html', 
    path('archive/', views.page_archive, name='archive'),

    #path('tasks/<int:contest_order>/<int:collection_order>/<int:task_order>', views.tasks.page_task, name='task'),
    path('tasks/<int:contest_order>/<int:collection_order>', views.tasks.page_task_collection, name='tasks'),
    path('tasks/', views.tasks.page_task_collection_current, name='tasks_newest'),

    #path('solutions/<int:contest_order>/<int:collection_order>', views.tasks.page_sample_solutions, name='sample_solutions'),

    path('results/<int:contest_order>/<int:collection_order>/cumulative', views.results.PageResults.as_view(cumulative=True), name='results_cumulative'),
    path('results/<int:contest_order>/<int:collection_order>', views.results.PageResults.as_view(), name='results'),
    path('results/<int:contest_order>', views.results.PageResults.as_view(), name='results_contest'),
    path('results/', views.results.PageResults.as_view(), name='results_newest'),

    path('old_contribs/', views.PageOldContribs.as_view(), name='old_contribs_def'),
    path('old_contribs/<int:page_no>', views.PageOldContribs.as_view(), name='old_contribs'),
    path('rules/', views.PageRules.as_view(tags=['rules']), name='rules'),
    path('about/', views.PageAboutUs.as_view(tags=['about']), name='about'),
    #path('other_seminars/', views.PageOtherSeminars.as_view(tags=['other_seminars']), name='other_seminars'),
    path('how_to/', views.PageHowTo.as_view(tags=['how_to']), name='how_to'),
    path('user/submission/<int:contest_order>/<int:collection_order>/<int:task_order>', handlers.user_submission, name='user_submission'),
    path('user/submission/<int:contest_order>/<int:collection_order>/<int:task_order>/delete', handlers.user_submission_delete, name='user_submission_delete'),
    path('user/submission/<int:contest_order>/<int:collection_order>/<int:task_order>/write', views.page_write_submission, name='user_submission_write'),
    path('user/submission/<int:contest_order>/<int:collection_order>/<int:task_order>/save', handlers.user_submission_save, name='user_submission_save'),

    path('page/<path:path>', page_static, name='static_page'),
]

django-web/core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', include('smuggler.urls')),
    path('admin/', admin.site.urls),

    path('api/md_to_html', views.handler_markdown_to_html, name='md_to_html'),
    path('api/latex_to_html', views.handler_latex_to_html, name='latex_to_html'),
    path('api/', include('contest.api')),

    path('mathrace/', include('mathrace.urls', namespace='mathrace')),
    path('', include('contest.urls', namespace='brkos')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path('%s<path:path>' % settings.PRIVATE_URL, views.private_serve, {'document_root': settings.PRIVATE_ROOT}),
    path('%s<path:path>' % settings.PROTECTED_URL, views.protected_serve, {'document_root': settings.PROTECTED_ROOT}),
]

django-web/contest/views/handlers.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http import Http404, HttpResponse, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.template.loader import select_template
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.utils import timezone
from django.db.models import Prefetch
from django.db.models.functions import Lower

from contest.models import Contest, TaskCollection, TaskFileSubmission, Task, Contestant
from core.forms import UploadForm
from core.models import MediaFile, Organizer, ContestType
from forum.models import Contribution
from django.views.generic import TemplateView

from core.views import EditablePage, render_editable
from django.forms import Form

import json

"""
Views
"""

@staff_member_required(redirect_field_name='/')
def collection_file_upload(request, collection_id):
    form = UploadForm(['pdf'],4,request.POST,request.FILES)
    if not form.is_valid():
        return HttpResponseForbidden(form.errors["file"])

    f = request.FILES['file']
    collection = get_object_or_404(TaskCollection, pk=collection_id)
    file_type = request.GET["file_type"]
    attrname = f"{file_type}_pdf"
    target_filename = f'brkos/{file_type}_{collection.contest.order}_{collection.order}'

    collection.upload_file(attrname, f, target_filename, [request.user], 1)

    return HttpResponse('Soubor byl úspěšně nahrán.')


@staff_member_required(redirect_field_name='/')
def feedback_upload(request, submission_id):
    form = UploadForm(['pdf','jpg','jpeg','png'],4,request.POST,request.FILES)
    if not form.is_valid():
        return HttpResponseForbidden(form.errors["file"])

    f = request.FILES['file']
    submission = get_object_or_404(TaskFileSubmission, pk=submission_id)
    target_filename = 'feedbacks/'+submission.compose_file_name_feedback()

    submission.upload_file('feedback_file', f, target_filename, owners=[submission.contestant.user, request.user])

    return HttpResponse('Soubor byl úspěšně nahrán.')


@staff_member_required(redirect_field_name='/')
def multiple_upload(request, task_id):
    
    task = get_object_or_404(Task, pk=task_id)
    problem_files = []

    for fname, f in request.FILES.items():
        info = fname.split('_')

        try:
            submission = TaskFileSubmission.get_from_id62(info[0])

            target_filename = 'feedbacks/'+submission.compose_file_name_feedback()

            submission.upload_file('feedback_file', f, target_filename, owners=[submission.contestant.user, request.user])
        except:
            problem_files.append(fname)

    if len(problem_files) == 0:
        return HttpResponse('Soubor byl úspěšně nahrán.')
    else:
        msg = 'Některé soubory se nepodařilo nahrát:'
        for pf in problem_files: msg += '\n'+pf
        return HttpResponse(msg)


@login_required(redirect_field_name='/')
def user_submission(request, contest_order, collection_order, task_order):
    """
    Uploads contestant task submission to the private storage.
    Creates a new submission object in the database.

    Fails if contest, collection or task does not exist or the collection is not active.

    Privacy policy: LOGIN_REQUIRED

    :param request: HTTP request
    :param contest_order: (int)  order of the contest
    :param collection_order: (int) order of the collection int the contest
    :param task_order: (int) order of the task in the collection
    :return: HTTP response
    """

    form = UploadForm(['pdf','jpg','jpeg','png'],4,request.POST,request.FILES)
    if not form.is_valid():
        return HttpResponseForbidden(form.errors["file"])

    f = request.FILES['file']

    task = Task.objects.get(
        collection__order=collection_order,
        collection__contest__order=contest_order,
        order=task_order
    )

    if task.collection.is_closed():
        return HttpResponseForbidden('Nelze odevzdávat po uzavření série.')

    try:
        contestant = request.user.contestant
    except ObjectDoesNotExist:
        return HttpResponseForbidden('Může odevzdávat pouze registrovaný soutěžící.')

    if not contestant.is_allowed():
        return HttpResponseForbidden('Může odevzdávat pouze student střední školy.')

    try:
        submission = TaskFileSubmission.objects.get(contestant=contestant, task=task)
        try:
            submission.content.delete()
        except:
            pass
    except ObjectDoesNotExist:
        submission = TaskFileSubmission(
            contestant=contestant,
            task=task,
        )
        submission.save()

    media_file = MediaFile.objects.create(
        content=f,
        access=2,
        name="submissions/"+submission.compose_file_name()
    )

    media_file.owners.add(request.user)

    submission.score = None
    submission.content = media_file
    submission.save()

    return HttpResponse('Soubor byl úspěšně nahrán.')


@login_required(redirect_field_name='/')
def user_submission_delete(request, contest_order, collection_order, task_order):

    task = Task.objects.get(
        collection__order=collection_order,
        collection__contest__order=contest_order,
        order=task_order
    )

    if task.collection.is_closed():
        return HttpResponseForbidden('Nelze smazat řešení po uzavření série.')

    try:
        contestant = request.user.contestant
    except ObjectDoesNotExist:
        return HttpResponseForbidden('Může odevzdávat pouze registrovaný soutěžící.')

    if not contestant.is_allowed():
        return HttpResponseForbidden('Může odevzdávat pouze student střední školy.')

    try:
        submission = TaskFileSubmission.objects.get(contestant=contestant, task=task)
        submission.content.delete()
    except ObjectDoesNotExist:
        return HttpResponseForbidden('Nebyla dříve odevzdána žádná úloha.')

    submission.content = None
    submission.save()
    submission.delete_if_empty()

    return HttpResponse('Soubor byl odstraněn.')


@login_required(redirect_field_name='/')
def user_submission_save(request, contest_order, collection_order, task_order):

    content = request.POST['submission']

    task = Task.objects.get(
        collection__order=collection_order,
        collection__contest__order=contest_order,
        order=task_order
    )

    if task.collection.is_closed():
        return HttpResponseForbidden('Nelze odevzdat řešení po uzavření série.')

    try:
        contestant = request.user.contestant
    except ObjectDoesNotExist:
        return HttpResponseForbidden('Může odevzdávat pouze registrovaný soutěžící.')

    if not contestant.is_allowed():
        return HttpResponseForbidden('Může odevzdávat pouze student střední školy.')

    try:
        submission = TaskFileSubmission.objects.get(contestant=contestant, task=task)
    except ObjectDoesNotExist:
        submission = TaskFileSubmission(
            contestant=contestant,
            task=task
        )

    submission.online_submission = content
    submission.save()
    submission.delete_if_empty()

    return HttpResponse('Řešení bylo uloženo.')

django-web/contest/views/results.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.views.generic import TemplateView

from contest.models import Contest, TaskCollection, ResultsTable
from core.models import PublishableModel
from core.utils import int_to_roman

"""
Helpers
"""


def render_latex_results(request, head, res, contest, collection=None, cumulative=False):
    template_name = 'contest/latex/results.tex'

    contest_year_roman = int_to_roman(contest.order)
    if cumulative:
        title = 'Výsledky po {}. sérii {}. ročníku'.format(collection.order, contest_year_roman)
    else:
        title = 'Výsledky {}. série {}. ročníku'.format(collection.order, contest_year_roman)

    column_definition = '|r|l|c|l|' + 'c|' * (len(head)-4)

    context = {
        'collection': collection,
        'contest': contest,
        'head': head,
        'results': res,
        'column_definition': column_definition,
        'title': title,
    }

    return HttpResponse(render_to_string(template_name, context), content_type='text/plain')


"""
Views
"""


def find_collection(contest_order=None, collection_order=None):
    try:
        if contest_order is None:
            contest = Contest.public_objects()\
                .order_by('-order').first()
        else:
            contest = Contest.public_objects().get(order=contest_order)
    except (ObjectDoesNotExist, IndexError):
        raise Http404("Soutěž nenalezena.")

    if collection_order is None:
        collection = TaskCollection.current_collection_with_results()
    else:
        collection = contest.task_collections.filter(PublishableModel.q_public(), order=collection_order).last()
    if collection is None:
        raise Http404("Pro tuto soutěž zatím není zveřejněna žádná série.")

    return contest, collection


class PageResults(TemplateView):
    template_name = 'contest/results.html'
    cumulative = False

    def get_context_data(self, **kwargs):
        contest, collection = find_collection(kwargs.get('contest_order', None),
                                              kwargs.get('collection_order', None))
        table = ResultsTable(contest, collection)
        if collection.release_results:
            if self.cumulative:
                head, res = table.get_results_cumulative()
            else:
                head, res = table.get_results_collection()
        else:
            res = []
            head = []

        contests = Contest.objects.all()
        collections = contest.task_collections.all()

        return {
            'results': res,
            'displayed_contest': contest,
            'displayed_collection_order': collection.order,
            'contests': contests,
            'task_collections': collections,
            'this_contest_order': contest.order,
            'head': zip(range(1, len(head) + 1), head),
            'cumulative': self.cumulative,
        }


def handler_latex_results_cumulative(request, id):
    collection = get_object_or_404(TaskCollection, pk=id)
    head, res = ResultsTable(collection.contest, collection).get_results_cumulative()
    return render_latex_results(request, head, res, collection.contest, collection, cumulative=True)


def handler_latex_results(request, id):
    collection = get_object_or_404(TaskCollection, pk=id)
    head, res = ResultsTable(collection.contest, collection).get_results_collection()
    return render_latex_results(request, head, res, collection.contest, collection)

django-web/contest/templates/core/parts/menu.html
<ul class="menu p-4 overflow-y-auto w-80 bg-base-100 text-base-content">
    <!-- Sidebar content here -->
    <li><a class="px-4" href="{% url 'contest:tasks_newest' %}">
        Úlohy
    </a></li>
    <li><a class="px-4" href="{% url 'contest:results_newest' %}">
        Výsledky
    </a></li>
    <li><a class="px-4" href="{% url 'contest:archive' %}">
        Archiv
    </a></li>
    <li><a class="px-4" href="{% url 'contest:camp:camp' %}">
        Soustředění
    </a></li>
    <li><a class="px-4" href="{% url 'contest:forum:topics' %}">
        Fórum
    </a></li>
    <li><a class="px-4" href="{% url 'contest:rules' %}">
        Pravidla
    </a></li>
    <li><a class="px-4" href="{% url 'contest:about' %}">
        O nás
    </a></li>

    <span class="md:hidden">
        <div class="divider"></div>
        {% if user.is_authenticated %}

        <a class="px-2" href="{% url 'contest:account' %}">
            <button class="font-medium btn btn-primary">{{ user.username }}</button>
        </a>

        <a class="px-2" href="{% url 'contest:logout' %}">
            <button class="font-medium btn btn-secondary">Odhlásit</button>
        </a>
        {% else %}
        <a class="px-2" href="{% url 'contest:login' %}">
            <button class="font-medium btn btn-primary mx-2">Přihlásit</button>
        </a>

        <a class="px-2" href="{% url 'contest:register' %}">
            <button class="font-medium btn btn-secondary">Registrovat</button>
        </a>
        {% endif %}

        {% if user.is_staff %}
        <br>
        <a class="px-2" href="/admin">
            <button class="font-medium btn btn-accent btn-outline rounded-full my-4">Administrace</button>
        </a>
        {% endif %}
        </span>

    <!-- <li><a class="px-4" href="{% url 'contest:tasks_newest' %}">
        Úlohy
    </a></li>
    <li><a class="px-4" href="{% url 'contest:tasks_newest' %}">
        Úlohy
    </a></li> -->
</ul>

django-web/contest/templates/core/parts/navbar.html
{% load extras %}

<!-- Navbar -->
<header class="bg-white shadow">
    <div class="container flex items-center justify-between px-8 py-4 mx-auto flex-row">
        <div class="flex items-center text-2xl">
            <a href="{% url 'contest:index' %}" class="font-brkos">
                BRKOS
            </a>
        </div>
        <div class="hidden xl:flex mt-4 font-medium md:text-xl sm:mt-0">
            <a class="px-4" href="{% url 'contest:tasks_newest' %}">
                Úlohy
            </a>
            <a class="px-4" href="{% url 'contest:results_newest' %}">
                Výsledky
            </a>
            <a class="px-4" href="{% url 'contest:archive' %}">
                Archiv
            </a>
            <a class="px-4" href="{% url 'contest:camp:camp' %}">
                Soustředění
            </a>
            <a class="px-4" href="{% url 'contest:forum:topics' %}">
                Fórum
            </a>
            <a class="px-4" href="{% url 'contest:rules' %}">
                Pravidla
            </a>
            <a class="px-4" href="{% url 'contest:about' %}">
                O nás
            </a>
        </div>
        <div class="flex">
            <span class="hidden md:block">
            {% if user.is_authenticated %}

            {% if user.is_staff %}
            <a class="absolute right-16 top-28 z-10" href="/admin">
                <button class="font-medium btn btn-primary btn-accent btn-outline rounded-full w-32">Administrace</button>
            </a>
            {% if editable %}
            <a class="absolute right-16 top-44 z-10" onclick="$('#editable-list').toggle()">
                <button class="font-medium btn btn-primary btn-accent btn-outline rounded-full w-32">Editovat</button>
            </a>
            <div class="absolute right-16 top-60 z-10 hidden" id="editable-list">
                <ul class="w-32 rounded-lg border-accent border-2 overflow-hidden hover:border-accent-focus" style="border-radius: 24px;">
                {% for text in editable %}
                    <li class="text-center text-accent p-2 hover:bg-accent-focus hover:text-white cursor-pointer font-medium" onclick="window.open('{% url "admin:core_text_change" text.id %}')">{{text.name}}</li>
                {% endfor %}
                </ul>
            </div>
            {% endif %}
            {% endif %}

            <a class="px-2" href="{% url 'contest:account' %}">
                <button class="font-medium btn btn-primary">{{ user.username }}</button>
            </a>

            <a class="px-2" href="{% url 'contest:logout' %}">
                <button class="font-medium btn btn-secondary">Odhlásit</button>
            </a>
            {% else %}
            <a class="px-2" href="#my-modal">
                <button class="font-medium btn btn-primary mx-2">Přihlásit</button>
            </a>

            <a class="px-2" href="{% url 'contest:register' %}">
                <button class="font-medium btn btn-secondary">Registrovat</button>
            </a>
            {% endif %}
            </span>

            <div>
                <label for="my-drawer" class="drawer-button btn btn-circle mx-2 xl:hidden">
                    <svg class="swap-off fill-current" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 512 512"><path d="M64,384H448V341.33H64Zm0-106.67H448V234.67H64ZM64,128v42.67H448V128Z"/></svg>
                </label>
            </div>
        </div>

        {% include "core/parts/login_modal.html" %}
</header>

django-web/contest/templates/core/parts/stats.html
{% extends "admin/base_site.html" %}
{% block extrahead %}
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}
{% block content %}
    <h1>Statistika</h1>
    <h2>Statistika tohoto ročníku</h2>
    <p>Počet řešitelů v tomto ročníku: {{ this_contest_number }}</p>
    <div id="plot_by-grade"></div>
    <div id="plot_by-collection"></div>
    <h2>Statistika úloh</h2>
    <div id="plot_tasks-all"></div>
    <div id="plot_tasks-singly"></div>
    <h2>Průměrné bodové hodnocení úloh</h2>
    <table>
        <thead>
            <tr><th>Série</th><th>Úloha</th><th>Body</th></tr>
        </thead>
        <tbody>
            {% for task in tasks_scores %}
                <tr><td>{{ task.collection }}</td><td>{{ task.name }}</td><td>{{ task.score }}</td></tr>
            {% endfor %}
        </tbody>
    </table>
    <script>
        var data1 = [{x: ["1.","2.","3.","4."], y: [{{ bygrade.g1 }},{{ bygrade.g2 }},{{ bygrade.g3 }},{{ bygrade.g4 }}], type: "bar"}];
        var layout1 = {xaxis: {title: "Ročník"}, yaxis: {range: [0, 50]}, title: "Počet řešitelů podle ročníku"};
        Plotly.newPlot("plot_by-grade",data1,layout1);

        var data2 = [{x: [{% for collection in collections %} {{collection.order}},{% endfor %}], y: [{% for collection in collections %} {{collection.contestants}},{% endfor %}], mode: "lines", type: "scatter"}];
        var layout2 = {xaxis: {title: "Série", range: [0,6]}, yaxis: {range: [0, 100]}, title: "Počet řešitelů podle sérií"};
        Plotly.newPlot("plot_by-collection",data2,layout2);

        var data3 = [{x: [{% for collection in collections %} {{collection.order}},{% endfor %}], y: [{% for collection in collections %} {{collection.submissions}},{% endfor %}], mode: "lines", type: "scatter"}];
        var layout3 = {xaxis: {title: "Série", range: [0,6]}, yaxis: {range: [0, 450]}, title: "Počet odevzdaných úloh"};
        Plotly.newPlot("plot_tasks-all",data3,layout3);

        var data4 = [
        {% for task in tasks_submissions %}
        {x: [{% for collection in task.collections %} {{collection.order}},{% endfor %}], y: [{% for collection in task.collections %} {{collection.submissions}},{% endfor %}], name: "Úloha {{ task.name }}", mode: "lines", type: "scatter"},
        {% endfor %}
        ];
        var layout4 = {xaxis: {title: "Série", range: [0,6]}, yaxis: {range: [0, 80]}, title: "Počet odevzdaných úloh po úlohách"};
        Plotly.newPlot("plot_tasks-singly",data4,layout4);
    </script>
{% endblock %}