django-web/camp/urls.py
from django.urls import path
from camp import views

app_name = 'camp'

urlpatterns = [
    path('', views.PageCamp.as_view(tags=['pretext']), name='camp'),
    path('more', views.PageCamp.as_view(tags=['pretext'],more=True), name='camp_more'),
]

django-web/core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', include('smuggler.urls')),
    path('admin/', admin.site.urls),

    path('api/md_to_html', views.handler_markdown_to_html, name='md_to_html'),
    path('api/latex_to_html', views.handler_latex_to_html, name='latex_to_html'),
    path('api/', include('contest.api')),

    path('mathrace/', include('mathrace.urls', namespace='mathrace')),
    path('', include('contest.urls', namespace='brkos')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path('%s<path:path>' % settings.PRIVATE_URL, views.private_serve, {'document_root': settings.PRIVATE_ROOT}),
    path('%s<path:path>' % settings.PROTECTED_URL, views.protected_serve, {'document_root': settings.PROTECTED_ROOT}),
]

django-web/mathrace/urls.py
from django.urls import path, include
from mathrace import views
from core.views import page_static
from mathrace.views import users, tasks, results, handlers
from contest.views import users as br_users

app_name = 'mathrace'

urlpatterns = [
    path('login/', views.users.page_login, name='login'),
    path('logout/', views.users.handler_logout, name='logout'),
    path('register/', views.users.page_register, name='register'),
    path('reset_password/', br_users.page_reset_password, name='reset_password'),
    path('reset_password/confirm/<uidb64>/<token>/', br_users.page_reset_password_confirm, name='reset_password_confirm'),
    path('reset_password/done/', br_users.page_reset_password_done, name='reset_password_done'),

    path('verification/info', br_users.PageVerificationInfo.as_view(tags=['verification']), name='verification_info'),
    path('verification/send', br_users.page_verification_send, name='verification_send'),
    path('verification/verify/<uidb64>/<str:token>/', br_users.page_verification_verify, name='verification_verify'),

    
    path('account/view_change_password/', br_users.page_change_password, name='change_password'),
    path('account/', lambda request: views.users.page_account(request,None), name='account'),
    path('account/<str:tag>', views.users.page_account, name='account_tagged'),
    path('update_account/', views.users.page_update_account, name='update_account'),

    path('forum/', include('forum.urls')),
    
    path('', views.PageIndex.as_view(tags=['claim', 'subclaim', 'intro']), name='index'), #template_name='contest/index.html', 
    path('archive/', views.page_archive, name='archive'),
    
    path('teams/', lambda request: views.page_teams(request,None), name='teams'),
    path('teams/<int:contest_order>', views.page_teams_old, name='teams_old'),
    path('teams/<str:tag>', views.page_teams, name='teams_tagged'),
    #path('register_team/', lambda request: views.page_register_team(request,None), name='register_team'),
    #path('register_team/<str:tag>', views.page_register_team, name='register_team_tagged'),
    path('update_team/', views.page_update_team, name='update_team'),
    path('update_team/delete_photo', handlers.delete_team_photo, name='delete_team_photo'),
    path('update_team/upload_photo', handlers.upload_team_photo, name='upload_team_photo'),

    #path('tasks/<int:contest_order>/<int:collection_order>/<int:task_order>', views.tasks.page_task, name='task'),
    path('tasks/<int:contest_order>/<int:collection_order>', views.tasks.page_task_collection, name='tasks'),
    path('tasks/', views.tasks.page_task_collection_current, name='tasks_newest'),

    #path('solutions/<int:contest_order>/<int:collection_order>', views.tasks.page_sample_solutions, name='sample_solutions'),

    path('results/', views.results.PageResults.as_view(), name='results'),
    path('results/<int:contest_order>', views.results.PageResults.as_view(), name='old_results'),
    
    path('old_contribs/', views.PageOldContribs.as_view(), name='old_contribs_def'),
    path('old_contribs/<int:page_no>', views.PageOldContribs.as_view(), name='old_contribs'),
    path('rules/', views.PageRules.as_view(tags=['rules']), name='rules'),
    #path('about/', views.PageAboutUs.as_view(tags=['about']), name='about'),

    path('page/<path:path>', page_static, name='static_page'),
]

django-web/mathrace/forms.py
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.core.validators import FileExtensionValidator, MinValueValidator, MaxValueValidator
from mathrace.models import Team
from django.utils import timezone

from django.template import loader
from django.contrib.auth import get_user_model
from django.conf import settings
from django.core.mail import EmailMessage
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.core.exceptions import ValidationError

from core import forms
from contest.widgets import SchoolWidget
from core.widgets import CheckboxGDPRWidget

User = get_user_model()


class RegisterTeamFormNoGDPR(forms.ModelForm):
    name = forms.CharField(required=True, max_length=30, label="Název", labeled=True)
    underground = forms.BooleanField(required=False, label="Underground")
    school = forms.CharField(widget=SchoolWidget, required=False, max_length=250, label="Škola")
    second_member = forms.CharField(required=True, max_length=60, label="Jméno a příjmení 2. člena", labeled=True)
    third_member = forms.CharField(required=False, max_length=60, label="Jméno a příjmení 3. člena", labeled=True)
    fourth_member = forms.CharField(required=False, max_length=60, label="Jméno a příjmení 4. člena", labeled=True)

    def clean(self):
        data = self.cleaned_data

        if not data.get('underground',False) and not data.get('school',None):
            self.add_error('school',forms.ValidationError('Zadejte školu'))
        if data.get('underground',False):
            data['school'] = None

        if not data.get('third_member',None) and data.get('fourth_member',None):
            data['third_member'] = data['fourth_member']
            data['fourth_member'] = None

        return data

    class Meta:
        model = Team
        fields = ['name', 'underground', 'school', 'second_member', 'third_member', 'fourth_member']


class RegisterTeamForm(RegisterTeamFormNoGDPR):
    name = forms.CharField(required=True, max_length=30, label="Název", labeled=False)
    second_member = forms.CharField(required=True, max_length=60, label="Jméno a příjmení 2. člena", labeled=False)
    third_member = forms.CharField(required=False, max_length=60, label="Jméno a příjmení 3. člena", labeled=False)
    fourth_member = forms.CharField(required=False, max_length=60, label="Jméno a příjmení 4. člena", labeled=False)
    gdpr = forms.BooleanField(widget=CheckboxGDPRWidget(attrs={'gdpr_url':'/static/mathrace/GDPR.pdf'}), required=True, label="Souhlasím s podmínkami zpracování osobních údajů")

django-web/contest/views/results.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.views.generic import TemplateView

from contest.models import Contest, TaskCollection, ResultsTable
from core.models import PublishableModel
from core.utils import int_to_roman

"""
Helpers
"""


def render_latex_results(request, head, res, contest, collection=None, cumulative=False):
    template_name = 'contest/latex/results.tex'

    contest_year_roman = int_to_roman(contest.order)
    if cumulative:
        title = 'Výsledky po {}. sérii {}. ročníku'.format(collection.order, contest_year_roman)
    else:
        title = 'Výsledky {}. série {}. ročníku'.format(collection.order, contest_year_roman)

    column_definition = '|r|l|c|l|' + 'c|' * (len(head)-4)

    context = {
        'collection': collection,
        'contest': contest,
        'head': head,
        'results': res,
        'column_definition': column_definition,
        'title': title,
    }

    return HttpResponse(render_to_string(template_name, context), content_type='text/plain')


"""
Views
"""


def find_collection(contest_order=None, collection_order=None):
    try:
        if contest_order is None:
            contest = Contest.public_objects()\
                .order_by('-order').first()
        else:
            contest = Contest.public_objects().get(order=contest_order)
    except (ObjectDoesNotExist, IndexError):
        raise Http404("Soutěž nenalezena.")

    if collection_order is None:
        collection = TaskCollection.current_collection_with_results()
    else:
        collection = contest.task_collections.filter(PublishableModel.q_public(), order=collection_order).last()
    if collection is None:
        raise Http404("Pro tuto soutěž zatím není zveřejněna žádná série.")

    return contest, collection


class PageResults(TemplateView):
    template_name = 'contest/results.html'
    cumulative = False

    def get_context_data(self, **kwargs):
        contest, collection = find_collection(kwargs.get('contest_order', None),
                                              kwargs.get('collection_order', None))
        table = ResultsTable(contest, collection)
        if collection.release_results:
            if self.cumulative:
                head, res = table.get_results_cumulative()
            else:
                head, res = table.get_results_collection()
        else:
            res = []
            head = []

        contests = Contest.objects.all()
        collections = contest.task_collections.all()

        return {
            'results': res,
            'displayed_contest': contest,
            'displayed_collection_order': collection.order,
            'contests': contests,
            'task_collections': collections,
            'this_contest_order': contest.order,
            'head': zip(range(1, len(head) + 1), head),
            'cumulative': self.cumulative,
        }


def handler_latex_results_cumulative(request, id):
    collection = get_object_or_404(TaskCollection, pk=id)
    head, res = ResultsTable(collection.contest, collection).get_results_cumulative()
    return render_latex_results(request, head, res, collection.contest, collection, cumulative=True)


def handler_latex_results(request, id):
    collection = get_object_or_404(TaskCollection, pk=id)
    head, res = ResultsTable(collection.contest, collection).get_results_collection()
    return render_latex_results(request, head, res, collection.contest, collection)

django-web/mathrace/views/handlers.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http import Http404, HttpResponse, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.template.loader import select_template
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.utils import timezone
from django.db.models import Prefetch

from mathrace.forms import RegisterTeamForm, RegisterTeamFormNoGDPR
from mathrace.models import Contest,TaskCollection, Task, Team
from core.forms import UploadForm
from core.models import MediaFile, Organizer, ContestType
from forum.models import Contribution
from django.views.generic import TemplateView

from core.views import EditablePage, render_editable
from core.utils import frinedly_base62_encode

import json

"""
Views
"""


@staff_member_required(redirect_field_name='/')
def collection_file_upload(request, collection_id):
    form = UploadForm(['pdf'],4,request.POST,request.FILES)
    if not form.is_valid():
        return HttpResponseForbidden(form.errors["file"])

    f = request.FILES['file']
    collection = get_object_or_404(TaskCollection, pk=collection_id)
    file_type = request.GET["file_type"]
    attrname = f"{file_type}_pdf"
    target_filename = f'mathrace/{file_type}_{collection.contest.order}_{collection.order}'

    collection.upload_file(attrname, f, target_filename, [request.user], 1)

    return HttpResponse('Soubor byl úspěšně nahrán.')


@staff_member_required(redirect_field_name='/')
def contest_file_upload(request, contest_id):
    form = UploadForm(['html'],4,request.POST,request.FILES)
    if not form.is_valid():
        return HttpResponseForbidden(form.errors["file"])

    f = request.FILES['file']
    contest = get_object_or_404(Contest, pk=contest_id)
    file_type = request.GET["file_type"]
    attrname = f"{file_type}_html"
    target_filename = f'mathrace/{file_type}_{contest.order}'

    contest.upload_file(attrname, f, target_filename, [request.user], 0)

    return HttpResponse('Soubor byl úspěšně nahrán.')


@login_required(redirect_field_name='/')
def delete_team_photo(request):

    team = Team.active_team(request)
    team.photo.delete()
    team.photo = None
    team.save()

    return HttpResponse('Týmová fotka byla odstraněna.')


@login_required(redirect_field_name='/')
def upload_team_photo(request):
    team = Team.active_team(request)

    form = UploadForm(['jpg','jpeg','png'],4,request.POST,request.FILES)
    if not form.is_valid():
        return HttpResponseForbidden(form.errors["file"])

    try:
        team.photo.delete()
    except:
        pass

    f = request.FILES['file']

    id62 = frinedly_base62_encode(team.id)

    media_file = MediaFile.objects.create(
        content=f,
        access=0,
        name="team_photos/"+id62
    )

    media_file.owners.add(request.user)

    team.photo = media_file
    team.save()

    return HttpResponse('Týmová fotka byla úspěšně nahrána.')

django-web/mathrace/views/results.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.views.generic import TemplateView
from django.utils.html import format_html

from mathrace.models import Contest, TaskCollection
from core.models import PublishableModel
from core.utils import int_to_roman

"""
Helpers
"""


def render_latex_results(request, head, res, contest, collection=None, cumulative=False):
    template_name = 'contest/latex/results.tex'

    contest_year_roman = int_to_roman(contest.order)
    if cumulative:
        title = 'Výsledky po {}. sérii {}. ročníku'.format(collection.order, contest_year_roman)
    else:
        title = 'Výsledky {}. série {}. ročníku'.format(collection.order, contest_year_roman)

    column_definition = '|r|l|c|l|' + 'c|' * (len(head)-4)

    context = {
        'collection': collection,
        'contest': contest,
        'head': head,
        'results': res,
        'column_definition': column_definition,
        'title': title,
    }

    return HttpResponse(render_to_string(template_name, context), content_type='text/plain')


"""
Views
"""


def find_collection(contest_order=None, collection_order=None):

    try:
        if contest_order is None:
            contest = Contest.public_objects()\
                .order_by('-order').first()
        else:
            contest = Contest.public_objects().get(contest_type=contest_type,
                                                   order=contest_order)
    except (ObjectDoesNotExist, IndexError):
        raise Http404("Soutěž nenalezena.")

    if collection_order is None:
        collection = TaskCollection.current_collection_with_results(contest_type)
    else:
        collection = contest.task_collections.filter(PublishableModel.q_public(), order=collection_order).last()
    if collection is None:
        raise Http404("Pro tuto soutěž zatím není zveřejněna žádná série.")

    return contest, collection


class PageResults(TemplateView):
    template_name = 'mathrace/results.html'

    def get_context_data(self, **kwargs):
        contest_order = kwargs.get('contest_order', None)
        if contest_order is None:
            try: fr = open("core/static/mathrace/results.html").read()
            except: fr = None

            try: fs = open("core/static/mathrace/stats.html").read()
            except: fs = None

            return {"results_html": fr, "stats_html": fs, "contest_order": "aktuálního"}
        else:
            try:
                contest = Contest.objects.get(order=contest_order)
            except:
                raise Http404("Ročník nenalezen")

            try: fr = contest.scoreboard_html.content.open("r").read()
            except: fr = None

            try: fs = contest.scoreboard_html.content.open("r").read()
            except: fs = None

            return {"results_html": fr, "stats_html": fs, "contest_order": int_to_roman(int(contest_order))+"."}



def handler_latex_results_cumulative(request, id):
    collection = get_object_or_404(TaskCollection, pk=id)
    head, res = ResultsTable(collection.contest, collection).get_results_cumulative()
    return render_latex_results(request, head, res, collection.contest, collection, cumulative=True)


def handler_latex_results(request, id):
    collection = get_object_or_404(TaskCollection, pk=id)
    head, res = ResultsTable(collection.contest, collection).get_results_collection()
    return render_latex_results(request, head, res, collection.contest, collection)

django-web/mathrace/templates/mathrace/index.html
{% extends "core/base.html" %}
{% load extras %}
{% load static %}

{% block title %} úvod {% endblock %}

{% block content %}
<section id="domu" class="hero relative" style="min-height: 65vh;">
    <div class="hero-overlay landing-gradient-mathrace"></div>
    <div class="hero-content text-center lg:w-1/2 flex-col mb-20 mt-16 z-10">
        <h1 class="font-bold text-3xl lg:text-4xl xl:text-5xl">
            {{ claim | safe }}
        <!-- Každá myšlenka se počítá. -->
        </h1>
        <p class="text-lg font-light lg:text-xl text-center">
            {{ subclaim | safe }}
            <!-- BRKOS je matematická soutěž pro všechny středoškoláky, kteří&nbsp;se&nbsp;nebojí přemýšlet. -->
        </p>
        <div class="w-full">
            <a class="mx-2 md:mx-4" href="{% url 'mathrace:teams' %}">
                <button class=" btn btn-lg  btn-primary w-5/12 md:w-1/3">
                    Registrace
                </button>
            </a>
            <a class="mx-2 md:mx-4" href="{% url 'mathrace:rules' %}">
                <button class="btn btn-lg btn-secondary w-5/12 md:w-1/3">
                    Pravidla
                </button>
            </a>
        </div>
    </div>
    <img src="{% static 'core/img/silhouette.svg' %}" alt="Silueta Brna"
        class="absolute bottom-0 opacity-40 invisible md:visible w-96 left-10 mb-0">
    <img src="{% static 'core/img/silhouette.svg' %}" alt="Silueta Brna"
        class="absolute bottom-0 fill-current invisible md:visible w-80 left-14 -mb-2">
    <div class="w-32 rounded-full bg-white border-2 border-base-content absolute -bottom-16 mx-auto left-0 right-0 overflow-hidden">
            <img src="{% static 'core/img/brkosak_grey.svg' %}" class="w-32 m-0 p-4 ">
    </div>
</section>
<section class="pt-20">
    <div class="w-11/12 mx-auto flex flex-col md:flex-row">
        <div class="w-full md:w-1/2 md:pr-10 mb-12 md:mb-0">
            <div class="blog">
            {{ intro | gen_file_refs | markdown_to_html |safe }}
            </div>
        </div>
        <div class="w-full md:w-1/2 md:pl-10">
            {% if contest_start %}
            <div class="container mx-auto mb-10 md:mb-20">
                {% include 'mathrace/parts/inline_clock.html' %}
            </div>
            {% endif %}
            <div class="">
                <div class="container mx-auto links-secondary">
                    {% for contrib in contribs %}
                        {% include 'core/parts/contrib.html' %}
                        </br>
                    {% endfor %}
                    <p><a href="{% url 'mathrace:old_contribs_def' %}">Další novinky</a></p>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}

django-web/mathrace/templates/mathrace/register_team.html
{% extends "core/base.html" %}

{% load extras %}

{% block title %} registrace týmu {% endblock %}

{% block content %}
<section class="center-block my-10 lg:my-20">
    {% if msg %}
    <div class="alert alert-success mb-4">{{ msg }}</div>
    {% endif %}
    {% if team %}
    <div class="card bg-base-200 shadow-inner">
        <div class="card-body">
            <h2>Můj tým</h2>
            <p>
                <table class="hidden md:table">
                    <tr><td>Název:</td> <td><b>{{ team.name }}</b></td></tr>
                    <tr><td>Underground:</td> <td>{% if team.underground %}ANO{% else %}NE{% endif %}</td></tr>
                    {% if not team.underground %}
                    <tr><td>Škola:</td> <td>{{ team.school }}</td></tr>
                    {% endif %}
                    <tr><td>Kontaktní email:</td> <td>{{ team.email }}</td></tr>
                    <tr><td class="h-4"></td></tr>
                    <tr><td>1. člen:</td> <td>{{ team.first_member }}</td></tr>
                    <tr><td>2. člen:</td> <td>{{ team.second_member }}</td></tr>
                    <tr><td>3. člen:</td> <td>{{ team.third_member }}</td></tr>
                    <tr><td>4. člen:</td> <td>{{ team.fourth_member }}</td></tr>
                </table>
                <dl class="md:hidden">
                    <dt>Název:</dt> <dd><b>{{ team.name }}</b></dd>
                    <dt>Underground:</dt> <dd>{% if team.underground %}ANO{% else %}NE{% endif %}</dd>
                    {% if not team.underground %}
                    <dt>Škola:</dt> <dd>{{ team.school }}</dd>
                    {% endif %}
                    <dt>Kontaktní email:</dt> <dd>{{ team.email }}</dd>
                    <dt class="mt-4">1. člen:</dt> <dd>{{ team.first_member }}</dd>
                    <dt>2. člen:</dt> <dd>{{ team.second_member }}</dd>
                    <dt>3. člen:</dt> <dd>{{ team.third_member }}</dd>
                    <dt>4. člen:</dt> <dd>{{ team.fourth_member }}</dd>
                </dl>
            {% if team.photo %}
            <p>Týmová fotka:</p>
            <div class="w-64 h-56" style="background-image: url({{team.photo.url}}); background-position: center center; background-repeat: no-repeat; background-size: cover;"></div>
            {% endif %}
            <p><a href="{% url 'mathrace:update_team' %}" class="btn btn-outline btn-secondary mb-2">Upravit údaje</a>
            {% if team.photo %}
            <a class="btn btn-outline border-error text-error hover:bg-error hover:text-base-100 hover:border-error mb-2" onclick="cmp.request_reload('{% url 'mathrace:delete_team_photo' %}')">Smazat fotku</a>
            {% else %}
            <a class="btn btn-outline btn-secondary mb-2" id="upload-btn">Nahrát fotku</a>
            <script>
                cmp.spawn(cmp.UploadFile, 'upload-btn', props={
                url: "{% url 'mathrace:upload_team_photo' %}",
                children: "Nahrát fotku"
                });
            </script>
            {% endif %}
            </p>
        </div>
    </div>
    {% elif reg_closed %}
        <h1>Registrace týmu</h1>
        <p>Registrace byla uzavřena.</p>
    {% else %}
        <h1>Registrace týmu</h1>
        {{ instructions | gen_file_refs | markdown_to_html | safe }}
        {% if user.is_authenticated %}
        <div class="card bg-base-200 shadow-inner">
            <div class="card-body">
                <h2 class="pb-4">Registrační formulář</h2>
                <form method="POST" class="block mx-auto text-center max-w-sm" action="{% url 'mathrace:register_team' %}" >
                    {% csrf_token %}
                    {% include 'core/parts/form.html' with form=registration_form %}
                    <button type="submit" class="btn my-10 btn-block btn-primary">Zaregistrovat!</button>
                </form>
            </div>
        </div>
        {% else %}
        <div class="text-center hidden md:block"><a class="btn btn-primary btn-wide self-center" href="#my-modal">Přihlásit</a></div>
        <div class="text-center md:hidden"><a class="btn btn-primary btn-wide self-center" href="{% url "mathrace:login" %}">Přihlásit</a></div>
        {% endif %}

    {% endif %}
</section>
{% endblock %}

django-web/mathrace/templates/mathrace/results.html
{% extends "core/base.html" %}
{% load extras %}
{% load static %}


{% block title %} výsledky {% endblock %}

{% block head %}
    {% include 'core/parts/latex.html' %}
{% endblock %}

{% block content %}
<section class="py-10 center-block">
    {% autoescape off %}
    <h1 class="text-center my-10">Výsledky {{ contest_order }} ročníku</h1>
    <div class="overflow-x-auto px-2">{{ results_html | safe }}</div>
    {% if stats_html %}
    <h1 class="text-center my-10"> Statistika {{ contest_order }} ročníku</h1>
    <div class="overflow-x-auto px-2">{{ stats_html | safe }}</div>
    {% endif %}
    {% endautoescape %}

{% endblock %}

django-web/mathrace/templates/mathrace/task_collection.html
{% extends "core/base.html" %}
{% load extras %}
{% load static %}


{% block title %} úlohy {% endblock %}
{% block head %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Old+Standard+TT">
{% endblock %}

{% block content %}

{% include 'mathrace/parts/server_time.html' %}

<section class="center-block py-10">
    <div class="">
        <h1 class="text-center my-10">Zadání {{ collection.contest.order | romanize }}. ročníku</h1>

        <div class="navbar px-3 pb-1 shadow-lg bg-base-100 horizontal rounded-box my-10">
            {% for listed_collection in all_collections %}
            <a href="{% url 'mathrace:tasks' contest_order=collection.contest.order collection_order=listed_collection.order %}" tabindex="0" class="mb-2 btn {%if collection.order == listed_collection.order %}btn-primary{% endif %} mr-2">{{listed_collection.order}}. série</a>
                 <!-- <li class="text-center border-b-2 p-2 my-2">{{ task_collection.name }}</li> -->
            {% endfor %}
        </div>

        <h2 class="text-center mt-10 mb-3"> {{ collection.order }}. série</h2>
        <h2 class="text-center mt-0">{{ collection.name }} </h2> 

        <!-- <h1 class="text-center mx-auto">{{ collection.order }}. série <span class="mx-4">·</span> {{ contest }}</h1> -->

        <p class="text-center mx-auto">Konec odevzdávání: {{ collection.close_date }}</p>

        <div class="rounded-box w-full mt-16 flex flex-col md:flex-row flex-wrap">
            {% if collection.assignment_pdf %}
                <a class="btn btn-secondary rounded-full px-4 py-2 mr-2 mb-2" target="_blank" href="{{collection.assignment_pdf.content.url}}">Zadání: <i class="fas fa-file-pdf mx-2"></i></a>
            {% endif %}
            {% if collection.helptext_pdf %}
                <a class="btn btn-secondary rounded-full px-4 py-2 mr-2 mb-2" target="_blank" href="{{collection.helptext_pdf.content.url}}">Pomocný text: <i class="fas fa-question-circle mx-2"></i></a>
            {% endif %}
            {% if collection.release_solution and collection.solution_pdf %}
                <a class="btn btn-secondary rounded-full px-4 py-2 mr-2 mb-2" target="_blank" href="{{collection.solution_pdf.content.url}}">Vzorové řešení: <i class="fas fa-book mx-2"></i></a>
            {% endif %}

            <a class="btn btn-secondary rounded-full px-4 py-2 mr-2 mb-2" target="_blank" href="{% url 'mathrace:results' %}">Výsledky: <i class="fas fa-chart-bar mx-2"></i></a>

            {% if collection.is_closed %}
                <span class="btn-disabled btn btn-error  rounded-full px-4 py-2 mr-2 mb-2">Série uzavřena <i class="fas fa-minus-circle mx-2"></i></span>
            {% else %}
                <span class="btn-disabled btn btn-warning rounded-full px-4 py-2 mr-2 mb-2">Uzavření: {{ collection.close_date | time }} <i class="fas fa-hourglass-half mx-2"></i></span>
            {% endif %}
            
        </div>
    {% for task in tasks %}
        {% if task %}
            {% include 'mathrace/parts/task.html' %}
        {% endif %}
    {% endfor%}
    </div>
</section>

<!--<div class="fixed left-0 bottom-0 text-lg border p-1">Čas serveru: 12:34:56</div>-->

{% endblock %}

django-web/mathrace/templates/mathrace/update_team.html
{% extends "core/base.html" %}

{% load extras %}

{% block title %} registrace {% endblock %}

{% block content %}
<section class="center-block my-10 lg:my-20">
        <div class="card bg-base-200 shadow-inner">
            <div class="card-body">
                <h2 class="pb-4">Upravit údaje</h2>
                <form method="POST" class="block mx-auto text-center w-full max-w-sm" action="{% url 'mathrace:update_team' %}" >
                    {% csrf_token %}
                    {% include 'core/parts/form.html' with form=registration_form %}
                    <button type="submit" class="btn my-10 btn-block btn-primary">Uložit</button>
                </form>
            </div>
        </div>
</section>
{% endblock %}